### ISSUE TITLE
background.js is not used 

### ISSUE THREAD

**Issue by fdiblen** [MaastrichtU-Library/the-FAIR-extension#25]
the listener function in background.js is not doing anything and not used anywhere. To keep things simple, I suggest removing it now and adding when it is needed.

**Comment by Alialsaeedi1** [comment]
background.js is actually being trigerred when a user tries to evaluate a DOI. It sends that specific DOI to background.js which saves it to chrome storage, and this allows popup.js to use that DOI to generate results. It also helps in the redirection of the user to the DOI url when they click on DOI.
