### ISSUE TITLE
Getting an error when trying to click on the buttons DOI or Evaluate

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-Library/the-FAIR-extension#32]
I am getting an error when trying to click on the buttons DOI or Evaluate:

![Screenshot from 2022-10-26 16-51-08](https://user-images.githubusercontent.com/3778439/198059965-d31c36cb-41a8-4251-8381-3cb19ba2102e.png)

It does this for every buttons. I tried in this page: https://pubmed.ncbi.nlm.nih.gov/26978244

The extension was installed on Chromium Version 106.0.5249.119 (Official Build) (64-bit)

The extension was installed from https://chrome.google.com/webstore/detail/the-fair-extension/pjmiddoifhbhbfcppdbmaigdeoiochdg/related

**Comment by pedrohserrano** [comment]
Solved in branch #45 
The main branch should be working fine (see image)

![Screenshot 2023-07-14 at 23 22 40](https://github.com/MaastrichtU-Library/the-FAIR-extension/assets/12054964/2ba1f1c2-9cfb-4b57-b81b-63e9d35ca469)
**(Note the API call takes between 2 to 6 secs depending on the website)**

Version labelled as 1.1.0 to be updated in Chrome store.
