### ISSUE TITLE
HTML popup is not apprearing 

### ISSUE THREAD

**Issue by Alialsaeedi1** [MaastrichtU-Library/the-FAIR-extension#41]
After the last push to main, index.html would not appear to the user when the extension icon is clicked. This has to do with the way panels are organized in the popup. Since it is not easy to add new panel, I would suggest adding the copyrights section under the 4 current boxes(Findable, Interoperable .etc)

**Comment by Alialsaeedi1** [comment]
I tried to modify the code and I found out that we can edit it to look like the photo I will send now, does it look good?
<img width="411" alt="Screen Shot 2022-11-06 at 4 24 00 PM" src="https://user-images.githubusercontent.com/56258081/200170646-280c7308-52f6-4c90-a492-55e6c7c00937.png">

**Comment by pedrohserrano** [comment]
issue #41 have been implemented and the associated pull request has been submitted. The branch has been successfully merged into the main branch and the changes have been deployed.
