### ISSUE TITLE
Crashing websites

### ISSUE THREAD

**Issue by Alialsaeedi1** [MaastrichtU-Library/the-FAIR-extension#42]
The extension causes several websites to crash such as youtube. This is caused after injecting the new html script after detecting the DOI's. I noticed that this crash is caused due to deletion of some HTML elements. What I suggest is carefully trying to study how the code changes the script and try avoiding the deletion of elements.

**Comment by pedrohserrano** [comment]
Worked on branch #44 but isn't working. Branch will be deleted

**Comment by pedrohserrano** [comment]
Solved in branch #45 
Version labeled as 1.1.0
